// Code generated by Wire protocol buffer compiler. DO NOT EDIT.
// source: cmd/server/wire.go
package main

import (
	"time"

	"mcp-gateway-go-demo/internal/cache"
	"mcp-gateway-go-demo/internal/config"
	"mcp-gateway-go-demo/internal/handler"
	"mcp-gateway-go-demo/internal/proxy"
	"mcp-gateway-go-demo/internal/repository"
	"mcp-gateway-go-demo/internal/service"

	"go.uber.org/zap"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
)

// App 聚合应用的所有顶层组件（Wire 生成的 InitializeApp 的返回值）
type App struct {
	Config     *config.Config
	Logger     *zap.Logger
	DB         *gorm.DB
	ApiRepo    *repository.ApiToolRepo
	HttpProxy  *proxy.HttpProxy
	CBManager  *proxy.CircuitBreakerManager
	Cache      cache.ToolCache
	SessionMgr *handler.SessionManager
	McpHandler *handler.McpHandler
	Service    *service.McpService
}

// InitializeApp Wire 生成的依赖注入函数
// 自动解析依赖图：Config → DB → Repo → Service → McpHandler
func InitializeApp() (*App, error) {
	// 1. 配置
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}

	// 2. 日志
	logger, err := zap.NewProduction()
	if err != nil {
		return nil, err
	}

	// 3. 数据库
	db, err := gorm.Open(sqlite.Open(cfg.Database.DSN), &gorm.Config{
		Logger: gormlogger.Default.LogMode(gormlogger.Warn),
	})
	if err != nil {
		return nil, err
	}

	// 4. Repository
	apiRepo := repository.NewApiToolRepo(db)

	// 5. HTTP 代理
	httpProxy := proxy.NewHttpProxy()

	// 6. 熔断管理器
	cbManager := proxy.NewCircuitBreakerManager(proxy.CBConfig{
		MaxFailures:         cfg.CircuitBreaker.MaxFailures,
		Timeout:             time.Duration(cfg.CircuitBreaker.Timeout) * time.Second,
		HalfOpenMaxRequests: cfg.CircuitBreaker.HalfOpenMaxRequests,
	})

	// 7. 缓存
	var toolCache cache.ToolCache
	if cfg.Cache.Enabled && cfg.Cache.RedisAddr != "" {
		redisCache, err := cache.NewRedisCache(cache.RedisConfig{
			Addr: cfg.Cache.RedisAddr, Password: cfg.Cache.RedisPassword, DB: cfg.Cache.RedisDB,
		})
		if err == nil {
			toolCache = redisCache
		}
	}
	if toolCache == nil {
		toolCache = cache.NewMemCache()
	}

	// 8. 核心服务
	cacheTTL := time.Duration(cfg.Cache.TTL) * time.Second
	svc := service.NewMcpService(apiRepo, httpProxy, cbManager, toolCache, cacheTTL, logger)

	// 9. 会话管理器
	sessionMgr := handler.NewSessionManager()

	// 10. MCP Handler
	mcpHandler := handler.NewMcpHandler(sessionMgr, apiRepo, svc, logger)

	return &App{
		Config:     cfg,
		Logger:     logger,
		DB:         db,
		ApiRepo:    apiRepo,
		HttpProxy:  httpProxy,
		CBManager:  cbManager,
		Cache:      toolCache,
		SessionMgr: sessionMgr,
		McpHandler: mcpHandler,
		Service:    svc,
	}, nil
}
